language: java
sudo: false # faster builds

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

before_install:
  - pip install --user codecov

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -N

script:
  - mvn test -B -N

after_success:
  - codecov
